'use client'

import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Download, Share2 } from 'lucide-react'
import { useState } from 'react'

interface DoctorExportProps {
  cycleLength: number
  cyclesTracked: number
  patterns: string[]
}

export function InsightsDoctorExport({ cycleLength, cyclesTracked, patterns }: DoctorExportProps) {
  const [isExporting, setIsExporting] = useState(false)

  const handleExport = () => {
    setIsExporting(true)

    const exportText = `CYCLE HEALTH INSIGHTS SUMMARY
Generated: ${new Date().toLocaleDateString()}

CYCLE INFORMATION
- Average cycle length: ${cycleLength} days
- Cycles tracked: ${cyclesTracked}

OBSERVED PATTERNS
${patterns.map((p) => `• ${p}`).join('\n')}

KEY OBSERVATIONS
This summary represents tracked data and observations. These observations are not a diagnosis
and do not replace professional medical evaluation.

QUESTIONS TO ASK YOUR DOCTOR
□ What are these patterns potentially indicating?
□ Should I be concerned about any of these patterns?
□ What additional testing or tracking would be helpful?
□ Are there lifestyle changes that might help?
□ How often should I follow up about these patterns?

NOTE
This report was generated by a health tracking app and is intended to support conversations
with healthcare providers, not replace professional medical advice.`

    const element = document.createElement('a')
    element.setAttribute('href', `data:text/plain;charset=utf-8,${encodeURIComponent(exportText)}`)
    element.setAttribute('download', `cycle-insights-${new Date().getTime()}.txt`)
    element.style.display = 'none'
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)

    setIsExporting(false)
  }

  return (
    <Card className="p-6 bg-gradient-to-br from-blue-50 to-indigo-50 border-blue-200">
      <div className="space-y-4">
        <div>
          <h3 className="text-lg font-semibold text-foreground mb-1">Share with Your Doctor</h3>
          <p className="text-sm text-muted-foreground">
            Export your insights and patterns to discuss with your healthcare provider
          </p>
        </div>

        <div className="bg-white bg-opacity-70 rounded-lg p-4 space-y-2">
          <p className="text-sm font-medium text-foreground">Your export includes:</p>
          <ul className="text-sm text-muted-foreground space-y-1">
            <li className="flex gap-2">
              <span>→</span> Complete cycle tracking summary
            </li>
            <li className="flex gap-2">
              <span>→</span> Observed patterns and trends
            </li>
            <li className="flex gap-2">
              <span>→</span> Suggested questions for your doctor
            </li>
          </ul>
        </div>

        <div className="bg-blue-50 border border-blue-200 rounded-lg p-3">
          <p className="text-xs text-blue-900">
            This helps your doctor understand your health better and makes appointments more productive.
          </p>
        </div>

        <div className="flex gap-2 pt-2">
          <Button
            className="flex-1 gap-2"
            onClick={handleExport}
            disabled={isExporting}
            variant="default"
          >
            <Download className="h-4 w-4" />
            {isExporting ? 'Exporting...' : 'Export as Text'}
          </Button>
          <Button
            variant="outline"
            size="icon"
            title="Share"
            onClick={() => {
              if (navigator.share) {
                navigator.share({
                  title: 'My Cycle Health Insights',
                  text: 'Check out my cycle health insights from My Cycle app',
                })
              }
            }}
          >
            <Share2 className="h-4 w-4" />
          </Button>
        </div>
      </div>
    </Card>
  )
}
