import type {
  FoodSuggestion,
  CravingExplanation,
  PhaseNutritionInfo,
  NutritionCyclePhase,
} from './nutrition-types'

export const phaseNutritionInfo: Record<NutritionCyclePhase, PhaseNutritionInfo> = {
  menstrual: {
    phase: 'menstrual',
    label: 'Menstrual Phase',
    commonNeeds: ['Comfort', 'Warmth', 'Iron support', 'Emotional safety'],
    uiCopy: 'Warm, comforting foods can feel grounding during your period.',
    suggestedFoodCategories: ['Soups & stews', 'Warm drinks', 'Iron-rich meals', 'Comfort snacks'],
  },
  follicular: {
    phase: 'follicular',
    label: 'Follicular Phase',
    commonNeeds: ['Light energy', 'Nutrient rebuilding', 'Mental clarity'],
    uiCopy: 'Your body may feel lighter — simple nourishment works well here.',
    suggestedFoodCategories: ['Fresh fruits', 'Yogurt & curd bowls', 'Light salads', 'Simple balanced meals'],
  },
  ovulation: {
    phase: 'ovulation',
    label: 'Ovulation Phase',
    commonNeeds: ['Stable energy', 'Hydration', 'Gut balance'],
    uiCopy: 'Balanced meals can help maintain your energy and mood.',
    suggestedFoodCategories: ['Protein-rich meals', 'Fibre-rich vegetables', 'Hydrating foods', 'Whole grains'],
  },
  luteal: {
    phase: 'luteal',
    label: 'Luteal / PMS Phase',
    commonNeeds: ['Stress reduction', 'Blood sugar stability', 'Mood support'],
    uiCopy: 'Cravings are common here — pairing comfort with nourishment can help.',
    suggestedFoodCategories: ['Complex carbs', 'Magnesium-rich foods', 'Comfort snacks', 'Warm drinks'],
  },
}

export const foodSuggestions: FoodSuggestion[] = [
  // ── MENSTRUAL PHASE ──
  {
    id: 'warm-lentil-soup',
    name: 'Warm Lentil Soup',
    description: 'A bowl of dal with gentle spices, served warm. Simple, nourishing, and grounding.',
    timeEstimate: '20 min',
    moodBenefit: 'calming',
    cyclePhases: ['menstrual'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'comfort-cooking',
    symptomSupport: ['cramps', 'fatigue'],
    stressContext: 'Lentils provide steady energy and iron, which may support you when energy feels low.',
    cycleFriendlyNote: 'Supports comfort and energy during your period',
  },
  {
    id: 'khichdi-bowl',
    name: 'Khichdi Bowl',
    description: 'Soft rice and dal cooked together with mild turmeric. The gentlest comfort meal.',
    timeEstimate: '20 min',
    moodBenefit: 'comforting',
    cyclePhases: ['menstrual'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'comfort-cooking',
    symptomSupport: ['cramps', 'bloating', 'fatigue'],
    stressContext: 'Easy to digest and warming. Turmeric has gentle anti-inflammatory properties.',
    cycleFriendlyNote: 'Gentle on your stomach when everything feels tender',
  },
  {
    id: 'warm-milk-with-turmeric',
    name: 'Warm Milk with Turmeric',
    description: 'A cup of warm milk (dairy or plant-based) with a pinch of turmeric and honey.',
    timeEstimate: '10 min',
    moodBenefit: 'calming',
    cyclePhases: ['menstrual', 'luteal'],
    dietaryTags: ['veg', 'egg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['cramps', 'stress'],
    stressContext: 'Warmth and gentle spices can help ease tension and support calmer sleep.',
    cycleFriendlyNote: 'A warm ritual that often feels soothing',
  },
  {
    id: 'dark-chocolate-squares',
    name: 'Dark Chocolate',
    description: 'A few squares of dark chocolate. No guilt attached — this is allowed and welcome.',
    timeEstimate: 'No cook',
    moodBenefit: 'comforting',
    cyclePhases: ['menstrual', 'luteal'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['low-mood', 'stress', 'cramps'],
    stressContext: 'Dark chocolate contains magnesium, which is linked to muscle relaxation and calmer moods.',
    cycleFriendlyNote: 'Pleasure is part of nourishment',
  },
  {
    id: 'egg-toast-comfort',
    name: 'Egg on Toast',
    description: 'A warm, soft egg on toasted bread. Quick, filling, and kind.',
    timeEstimate: '10 min',
    moodBenefit: 'grounding',
    cyclePhases: ['menstrual'],
    dietaryTags: ['egg', 'non-veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['fatigue'],
    stressContext: 'Eggs provide protein and B vitamins, which support energy when you feel drained.',
    cycleFriendlyNote: 'Simple nourishment that holds you steady',
  },
  {
    id: 'ginger-tea',
    name: 'Ginger Tea',
    description: 'Freshly grated ginger steeped in hot water. A small cup of warmth.',
    timeEstimate: '10 min',
    moodBenefit: 'calming',
    cyclePhases: ['menstrual'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['cramps', 'bloating'],
    stressContext: 'Ginger may help ease nausea and bloating. The ritual of sipping something warm can be calming in itself.',
    cycleFriendlyNote: 'Gentle warmth for uncomfortable moments',
  },

  // ── FOLLICULAR PHASE ──
  {
    id: 'fruit-yogurt-bowl',
    name: 'Fruit and Yogurt Bowl',
    description: 'Fresh seasonal fruit with yogurt or curd. Light, refreshing, enough.',
    timeEstimate: '10 min',
    moodBenefit: 'energizing',
    cyclePhases: ['follicular'],
    dietaryTags: ['veg', 'egg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['fatigue'],
    stressContext: 'Probiotics in yogurt support gut health, and fresh fruit provides natural energy.',
    cycleFriendlyNote: 'Light nourishment for a lighter phase',
  },
  {
    id: 'sprout-salad',
    name: 'Sprout Salad',
    description: 'Mixed sprouts with lemon, salt, and a pinch of chaat masala. Crunchy and bright.',
    timeEstimate: '10 min',
    moodBenefit: 'energizing',
    cyclePhases: ['follicular'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['fatigue'],
    stressContext: 'Sprouts are rich in folate and protein, supporting your body as it rebuilds.',
    cycleFriendlyNote: 'Fresh and rebuilding',
  },
  {
    id: 'veggie-poha',
    name: 'Vegetable Poha',
    description: 'Flattened rice with peanuts, vegetables, and a squeeze of lemon. A familiar comfort.',
    timeEstimate: '15 min',
    moodBenefit: 'uplifting',
    cyclePhases: ['follicular'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['fatigue'],
    stressContext: 'Light carbohydrates provide quick energy without heaviness.',
    cycleFriendlyNote: 'Light, familiar, and satisfying',
  },
  {
    id: 'paneer-wrap',
    name: 'Paneer or Tofu Wrap',
    description: 'Soft roti with paneer or tofu, some greens, and a drizzle of chutney.',
    timeEstimate: '15 min',
    moodBenefit: 'grounding',
    cyclePhases: ['follicular', 'ovulation'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['fatigue'],
    stressContext: 'Protein supports your body through the rebuilding phase.',
    cycleFriendlyNote: 'Balanced and easy to carry with you',
  },

  // ── OVULATION PHASE ──
  {
    id: 'dal-rice-sabzi',
    name: 'Dal, Rice & Sabzi',
    description: 'A balanced plate. Dal for protein, rice for energy, sabzi for fibre. Nothing fancy, just right.',
    timeEstimate: '30 min',
    moodBenefit: 'grounding',
    cyclePhases: ['ovulation'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'comfort-cooking',
    symptomSupport: ['fatigue', 'stress'],
    stressContext: 'A balanced meal supports stable energy and mood throughout the day.',
    cycleFriendlyNote: 'Stable, steady, grounding',
  },
  {
    id: 'cucumber-raita',
    name: 'Cucumber Raita',
    description: 'Cool yogurt with grated cucumber, cumin, and a pinch of salt. Refreshing and easy.',
    timeEstimate: '10 min',
    moodBenefit: 'calming',
    cyclePhases: ['ovulation'],
    dietaryTags: ['veg', 'egg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['bloating'],
    stressContext: 'Hydrating and cooling. Probiotics in yogurt support digestion.',
    cycleFriendlyNote: 'Cooling and hydrating when your body runs warm',
  },
  {
    id: 'chicken-rice-bowl',
    name: 'Simple Chicken Rice Bowl',
    description: 'Steamed rice with seasoned chicken pieces and some greens on the side.',
    timeEstimate: '20 min',
    moodBenefit: 'grounding',
    cyclePhases: ['ovulation'],
    dietaryTags: ['non-veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['fatigue'],
    stressContext: 'Lean protein supports sustained energy during your most active phase.',
    cycleFriendlyNote: 'Protein-forward for an active phase',
  },
  {
    id: 'watermelon-mint',
    name: 'Watermelon with Mint',
    description: 'Chilled watermelon cubes with fresh mint leaves. Hydrating and cool.',
    timeEstimate: 'No cook',
    moodBenefit: 'uplifting',
    cyclePhases: ['ovulation'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['bloating'],
    stressContext: 'Watermelon is over 90% water — a delicious way to stay hydrated.',
    cycleFriendlyNote: 'Refreshing hydration that feels like a treat',
  },

  // ── LUTEAL / PMS PHASE ──
  {
    id: 'banana-oat-bowl',
    name: 'Banana Oat Bowl',
    description: 'Warm oats topped with sliced banana, a drizzle of honey, and a few nuts.',
    timeEstimate: '10 min',
    moodBenefit: 'comforting',
    cyclePhases: ['luteal'],
    dietaryTags: ['veg', 'egg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['low-mood', 'stress', 'fatigue'],
    stressContext: 'Bananas contain potassium and natural sugars that may help stabilize mood. Oats provide slow-release energy.',
    cycleFriendlyNote: 'Steady comfort when mood dips',
  },
  {
    id: 'nut-butter-toast',
    name: 'Toast + Nut Butter + Fruit',
    description: 'Toast with a spread of peanut or almond butter, topped with banana slices. Enough for now.',
    timeEstimate: 'No cook',
    moodBenefit: 'grounding',
    cyclePhases: ['luteal', 'menstrual'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['fatigue', 'low-mood'],
    stressContext: 'Nut butters provide protein and healthy fats. This is a valid, complete snack-meal.',
    cycleFriendlyNote: 'Enough for today',
  },
  {
    id: 'sweet-potato-bowl',
    name: 'Roasted Sweet Potato Bowl',
    description: 'Soft roasted sweet potato with a pinch of cinnamon and some seeds. Warm and satisfying.',
    timeEstimate: '30 min',
    moodBenefit: 'comforting',
    cyclePhases: ['luteal'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'comfort-cooking',
    symptomSupport: ['stress', 'low-mood'],
    stressContext: 'Sweet potatoes are a complex carb — they support steady blood sugar and serotonin production.',
    cycleFriendlyNote: 'Complex carbs for a complex phase',
  },
  {
    id: 'trail-mix-snack',
    name: 'Trail Mix',
    description: 'A handful of nuts, seeds, and a few dark chocolate chips. Carry it with you.',
    timeEstimate: 'No cook',
    moodBenefit: 'grounding',
    cyclePhases: ['luteal'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['fatigue', 'low-mood', 'stress'],
    stressContext: 'Nuts and seeds are rich in magnesium and zinc, which may support mood and reduce tension.',
    cycleFriendlyNote: 'Small, steady support throughout the day',
  },
  {
    id: 'warm-soup-any',
    name: 'Any Warm Soup',
    description: 'Tomato, mixed veg, or whatever you have. Warm liquid in a bowl is its own kind of medicine.',
    timeEstimate: '20 min',
    moodBenefit: 'calming',
    cyclePhases: ['luteal', 'menstrual'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['cramps', 'stress', 'bloating'],
    stressContext: 'Warm liquids support digestion and the act of sipping can help regulate your nervous system.',
    cycleFriendlyNote: 'Warmth in a bowl',
  },
  {
    id: 'chamomile-honey',
    name: 'Chamomile Tea with Honey',
    description: 'A gentle cup of chamomile with a spoonful of honey. Slow down, sip, breathe.',
    timeEstimate: '10 min',
    moodBenefit: 'calming',
    cyclePhases: ['luteal', 'menstrual'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['stress', 'cramps'],
    stressContext: 'Chamomile has been traditionally used to support relaxation and ease tension.',
    cycleFriendlyNote: 'A small, warm ritual for hard days',
  },

  // ── MULTI-PHASE / UNIVERSAL ──
  {
    id: 'curd-rice',
    name: 'Curd Rice',
    description: 'Soft rice mixed with fresh curd, tempered with mustard seeds. Cool, gentle, home.',
    timeEstimate: '15 min',
    moodBenefit: 'comforting',
    cyclePhases: ['menstrual', 'follicular', 'ovulation', 'luteal'],
    dietaryTags: ['veg', 'no-preference'],
    effort: 'quick',
    symptomSupport: ['bloating', 'stress'],
    stressContext: 'Probiotics in curd support gut health. This is one of the gentlest meals you can eat.',
    cycleFriendlyNote: 'Gentle enough for any phase',
  },
  {
    id: 'banana-plain',
    name: 'Just a Banana',
    description: 'Peel. Eat. Done. This counts as nourishment.',
    timeEstimate: 'No cook',
    moodBenefit: 'grounding',
    cyclePhases: ['menstrual', 'follicular', 'ovulation', 'luteal'],
    dietaryTags: ['veg', 'egg', 'non-veg', 'no-preference'],
    effort: 'no-cook',
    symptomSupport: ['fatigue', 'low-mood'],
    stressContext: 'Bananas provide quick energy and potassium. On low days, this is enough.',
    cycleFriendlyNote: 'Enough for right now',
  },
]

export const cravingExplanations: CravingExplanation[] = [
  {
    id: 'craving-chocolate',
    craving: 'Chocolate',
    explanation: 'During PMS and your period, your body may crave chocolate because it contains magnesium, which supports muscle relaxation. This is a normal, biological signal — not a weakness.',
    cyclePhases: ['luteal', 'menstrual'],
  },
  {
    id: 'craving-carbs',
    craving: 'Carbs and bread',
    explanation: 'During the luteal phase, your body may crave carbohydrates to support serotonin production. Serotonin helps regulate mood. Craving carbs is your body asking for mood support.',
    cyclePhases: ['luteal'],
  },
  {
    id: 'craving-salty',
    craving: 'Salty foods',
    explanation: 'Hormonal changes can affect fluid balance in your body, which sometimes creates a desire for salty foods. If you feel like having something salty, that is okay.',
    cyclePhases: ['luteal', 'menstrual'],
  },
  {
    id: 'craving-sweet',
    craving: 'Sweets and sugar',
    explanation: 'Blood sugar levels can fluctuate more during certain cycle phases. Sweet cravings may be your body looking for quick energy. Pairing something sweet with protein can help you feel more steady.',
    cyclePhases: ['luteal', 'menstrual'],
  },
  {
    id: 'craving-warm',
    craving: 'Warm foods and drinks',
    explanation: 'During menstruation, your body temperature can drop slightly and cramping may increase. Craving warm food is a natural comfort response — your body is asking for warmth and ease.',
    cyclePhases: ['menstrual'],
  },
  {
    id: 'craving-comfort',
    craving: 'Comfort food in general',
    explanation: 'Comfort food cravings are often tied to emotional regulation. Food that feels familiar and safe activates calming neural pathways. Eating for comfort is valid nourishment.',
    cyclePhases: ['menstrual', 'luteal'],
  },
]
